// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface AcmGetCertificatePolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * The ARN of the certificate to grant access to
   */
  certificateArn: pulumi.Input<string>;
}

/**
 * Gives permission to retrieve a certificate and its certificate chain from ACM
 */
export class AcmGetCertificatePolicy extends pulumi.ComponentResource {
  constructor(name: string, args: AcmGetCertificatePolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:AcmGetCertificatePolicy', name, args, opts);
    const opt = {
      parent: this,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'acm:GetCertificate',
            ],
            Resource: [
              pulumi.interpolate`${args.certificateArn}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}