// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface AMIDescribePolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;
}

/**
 * Gives permissions to describe AMIs
 */
export class AMIDescribePolicy extends pulumi.ComponentResource {
  constructor(name: string, args: AMIDescribePolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:AMIDescribePolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'ec2:DescribeImages',
            ],
            Resource: [
              pulumi.interpolate`*`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}