// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface AWSSecretsManagerGetSecretValuePolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * The ARN of the secret to grant access to
   */
  secretArn: pulumi.Input<string>;
}

/**
 * Grants permissions to GetSecretValue for the specified AWS Secrets Manager secret
 */
export class AWSSecretsManagerGetSecretValuePolicy extends pulumi.ComponentResource {
  constructor(name: string, args: AWSSecretsManagerGetSecretValuePolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:AWSSecretsManagerGetSecretValuePolicy', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'secretsmanager:GetSecretValue',
            ],
            Resource: [
              pulumi.interpolate`${args.secretArn}`,
            ],
          },
        ],
      }
    }, opts);
    this.registerOutputs({});
  }
}