// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface AWSSecretsManagerRotationPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the Lambda Function
   */
  functionName: pulumi.Input<string>;
}

/**
 * Grants permissions to APIs required to rotate a secret in AWS Secrets Manager
 */
export class AWSSecretsManagerRotationPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: AWSSecretsManagerRotationPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:AWSSecretsManagerRotationPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'secretsmanager:DescribeSecret',
              'secretsmanager:GetSecretValue',
              'secretsmanager:PutSecretValue',
              'secretsmanager:UpdateSecretVersionStage',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:secretsmanager:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:secret:*`,
            ],
            Condition: {
              StringEquals: {
                'secretsmanager:resource/AllowRotationLambdaArn': pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:lambda:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:function:${args.functionName}`,
              },
            },
          },
          {
            Effect: 'Allow',
            Action: [
              'secretsmanager:GetRandomPassword',
            ],
            Resource: [
              pulumi.interpolate`*`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}