// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface CloudFormationDescribeStacksPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;
}

/**
 * Gives permission to describe CloudFormation stacks
 */
export class CloudFormationDescribeStacksPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: CloudFormationDescribeStacksPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:CloudFormationDescribeStacksPolicy', name, args, opts);
    const opt = {
      parent: this,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'cloudformation:DescribeStacks',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:cloudformation:${aws.getRegionOutput({}, opts).name}:${aws.getCallerIdentityOutput({}, opts).accountId}:stack/*`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}