// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface CloudWatchDashboardPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;
}

/**
 * Gives permissions to put metrics to operate on CloudWatch Dashboards
 */
export class CloudWatchDashboardPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: CloudWatchDashboardPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:CloudWatchDashboardPolicy', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'cloudwatch:GetDashboard',
              'cloudwatch:ListDashboards',
              'cloudwatch:PutDashboard',
              'cloudwatch:ListMetrics',
            ],
            Resource: [
              pulumi.interpolate`*`,
            ],
          },
        ],
      }
    }, opts);
    this.registerOutputs({});
  }
}