// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface CodePipelineReadOnlyPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the CodePipeline pipeline
   */
  pipelineName: pulumi.Input<string>;
}

/**
 * Gives read permissions to get details about a CodePipeline pipeline
 */
export class CodePipelineReadOnlyPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: CodePipelineReadOnlyPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:CodePipelineReadOnlyPolicy', name, args, opts);
    const opt = {
      parent: this,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'codepipeline:ListPipelineExecutions',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:codepipeline:${aws.getRegionOutput({}, opts).name}:${aws.getCallerIdentityOutput({}, opts).accountId}:${args.pipelineName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}