// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface CodeCommitReadPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the CodeCommit Repository
   */
  repositoryName: pulumi.Input<string>;
}

/**
 * Gives permissions to read objects within a specific codecommit repository
 */
export class CodeCommitReadPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: CodeCommitReadPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:CodeCommitReadPolicy', name, args, opts);
    const opt = {
      parent: this,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'codecommit:GitPull',
              'codecommit:GetBranch',
              'codecommit:ListBranches',
              'codecommit:BatchDescribeMergeConflicts',
              'codecommit:DescribeMergeConflicts',
              'codecommit:GetMergeCommit',
              'codecommit:GetMergeOptions',
              'codecommit:BatchGetPullRequests',
              'codecommit:DescribePullRequestEvents',
              'codecommit:GetCommentsForPullRequest',
              'codecommit:GetCommitsFromMergeBase',
              'codecommit:GetMergeConflicts',
              'codecommit:GetPullRequest',
              'codecommit:ListPullRequests',
              'codecommit:GetBlob',
              'codecommit:GetFile',
              'codecommit:GetFolder',
              'codecommit:GetComment',
              'codecommit:GetCommentsForComparedCommit',
              'codecommit:BatchGetCommits',
              'codecommit:GetCommit',
              'codecommit:GetCommitHistory',
              'codecommit:GetDifferences',
              'codecommit:GetObjectIdentifier',
              'codecommit:GetReferences',
              'codecommit:GetTree',
              'codecommit:GetRepository',
              'codecommit:ListTagsForResource',
              'codecommit:GetRepositoryTriggers',
              'codecommit:TestRepositoryTriggers',
              'codecommit:GetBranch',
              'codecommit:GetCommit',
              'codecommit:GetUploadArchiveStatus',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:codecommit:${aws.getRegionOutput({}, opts).name}:${aws.getCallerIdentityOutput({}, opts).accountId}:${args.repositoryName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}