// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface CodePipelineReadOnlyPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the CodePipeline pipeline
   */
  pipelineName: pulumi.Input<string>;
}

/**
 * Gives read permissions to get details about a CodePipeline pipeline
 */
export class CodePipelineReadOnlyPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: CodePipelineReadOnlyPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:CodePipelineReadOnlyPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'codepipeline:ListPipelineExecutions',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:codepipeline:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:${args.pipelineName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}