// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface DynamoDBReadPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the DynamoDB Table
   */
  tableName: pulumi.Input<string>;
}

/**
 * Gives read only access to a DynamoDB Table
 */
export class DynamoDBReadPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: DynamoDBReadPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:DynamoDBReadPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'dynamodb:GetItem',
              'dynamodb:Scan',
              'dynamodb:Query',
              'dynamodb:BatchGetItem',
              'dynamodb:DescribeTable',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:dynamodb:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:table/${args.tableName}`,
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:dynamodb:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:table/${args.tableName}/index/*`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}