// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface DynamoDBReconfigurePolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the DynamoDB Table
   */
  tableName: pulumi.Input<string>;
}

/**
 * Gives access reconfigure to a DynamoDB Table
 */
export class DynamoDBReconfigurePolicy extends pulumi.ComponentResource {
  constructor(name: string, args: DynamoDBReconfigurePolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:DynamoDBReconfigurePolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'dynamodb:UpdateTable',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:dynamodb:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:table/${args.tableName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}