// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface EcsRunTaskPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * The family and revision (family:revision) of the task definition
   */
  taskDefinition: pulumi.Input<string>;
}

/**
 * Gives permission to start a new task for a task definition
 */
export class EcsRunTaskPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: EcsRunTaskPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:EcsRunTaskPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'ecs:RunTask',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:ecs:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:task-definition/${args.taskDefinition}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}