// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface ElasticMapReduceModifyInstanceGroupsPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * The unique identifier of the cluster
   */
  clusterId: pulumi.Input<string>;
}

/**
 * Gives permission to list details and modify settings for instance groups within a cluster
 */
export class ElasticMapReduceModifyInstanceGroupsPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: ElasticMapReduceModifyInstanceGroupsPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:ElasticMapReduceModifyInstanceGroupsPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'elasticmapreduce:ModifyInstanceGroups',
              'elasticmapreduce:ListInstanceGroups',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:elasticmapreduce:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:cluster/${args.clusterId}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}