// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface ElasticMapReduceAddJobFlowStepsPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * The unique identifier of the cluster
   */
  clusterId: pulumi.Input<string>;
}

/**
 * Gives permission to add new steps to a running cluster
 */
export class ElasticMapReduceAddJobFlowStepsPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: ElasticMapReduceAddJobFlowStepsPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:ElasticMapReduceAddJobFlowStepsPolicy', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'elasticmapreduce:AddJobFlowSteps',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput().partition}:elasticmapreduce:${aws.getRegionOutput().name}:${aws.getCallerIdentityOutput().accountId}:cluster/${args.clusterId}`,
            ],
          },
        ],
      }
    }, opts);
    this.registerOutputs({});
  }
}