// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface ElasticsearchHttpPostPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of Domain
   */
  domainName: pulumi.Input<string>;
}

/**
 * Gives POST and PUT permissions to Elasticsearch
 */
export class ElasticsearchHttpPostPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: ElasticsearchHttpPostPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:ElasticsearchHttpPostPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'es:ESHttpPost',
              'es:ESHttpPut',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:es:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:domain/${args.domainName}/*`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}