// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface ElasticsearchHttpPostPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of Domain
   */
  domainName: pulumi.Input<string>;
}

/**
 * Gives POST and PUT permissions to Elasticsearch
 */
export class ElasticsearchHttpPostPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: ElasticsearchHttpPostPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:ElasticsearchHttpPostPolicy', name, args, opts);
    const opt = {
      parent: this,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'es:ESHttpPost',
              'es:ESHttpPut',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:es:${aws.getRegionOutput({}, opts).name}:${aws.getCallerIdentityOutput({}, opts).accountId}:domain/${args.domainName}/*`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}