// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface EventBridgePutEventsPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the EventBridge EventBus
   */
  eventBusName: pulumi.Input<string>;
}

/**
 * Gives permissions to send events to EventBridge
 */
export class EventBridgePutEventsPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: EventBridgePutEventsPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:EventBridgePutEventsPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'events:PutEvents',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:events:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:event-bus/${args.eventBusName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}