// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface FirehoseWritePolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of Kinesis Firehose Delivery Stream
   */
  deliveryStreamName: pulumi.Input<string>;
}

/**
 * Gives permission to write to a Kinesis Firehose Delivery Stream
 */
export class FirehoseWritePolicy extends pulumi.ComponentResource {
  constructor(name: string, args: FirehoseWritePolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:FirehoseWritePolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'firehose:PutRecord',
              'firehose:PutRecordBatch',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:firehose:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:deliverystream/${args.deliveryStreamName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}