// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface KMSDecryptPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * ID of the KMS Key
   */
  keyId: pulumi.Input<string>;
}

/**
 * Gives permission to decrypt with KMS Key
 */
export class KMSDecryptPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: KMSDecryptPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:KMSDecryptPolicy', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'kms:Decrypt',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput().partition}:kms:${aws.getRegionOutput().name}:${aws.getCallerIdentityOutput().accountId}:key/${args.keyId}`,
            ],
          },
        ],
      }
    }, opts);
    this.registerOutputs({});
  }
}