// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface KMSEncryptPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * ID of the KMS Key
   */
  keyId: pulumi.Input<string>;
}

/**
 * Gives permission to encrypt with KMS Key
 */
export class KMSEncryptPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: KMSEncryptPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:KMSEncryptPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'kms:Encrypt',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:kms:${aws.getRegionOutput({}, opts).name}:${aws.getCallerIdentityOutput({}, opts).accountId}:key/${args.keyId}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}