// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface KMSEncryptPolicy_v2Args {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * ID of the KMS Key
   */
  keyId: pulumi.Input<string>;
}

/**
 * Gives permission to encrypt with KMS Key
 */
export class KMSEncryptPolicy_v2 extends pulumi.ComponentResource {
  constructor(name: string, args: KMSEncryptPolicy_v2Args, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:KMSEncryptPolicy_v2', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'kms:Encrypt',
              'kms:GenerateDataKey',
              'kms:GenerateDataKeyWithoutPlaintext',
              'kms:GenerateDataKeyPair',
              'kms:GenerateDataKeyPairWithoutPlaintext',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput().partition}:kms:${aws.getRegionOutput().name}:${aws.getCallerIdentityOutput().accountId}:key/${args.keyId}`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}