// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface LambdaInvokePolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the Lambda Function
   */
  functionName: pulumi.Input<string>;
}

/**
 * Gives permission to invoke a Lambda Function, Alias or Version
 */
export class LambdaInvokePolicy extends pulumi.ComponentResource {
  constructor(name: string, args: LambdaInvokePolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:LambdaInvokePolicy', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'lambda:InvokeFunction',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput().partition}:lambda:${aws.getRegionOutput().name}:${aws.getCallerIdentityOutput().accountId}:function:${args.functionName}*`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}