// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface PinpointEndpointAccessPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * The id of your Pinpoint application
   */
  pinpointApplicationId: pulumi.Input<string>;
}

/**
 * Gives permissions to get and update endpoints for a Pinpoint application
 */
export class PinpointEndpointAccessPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: PinpointEndpointAccessPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:PinpointEndpointAccessPolicy', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'mobiletargeting:GetEndpoint',
              'mobiletargeting:UpdateEndpoint',
              'mobiletargeting:UpdateEndpointsBatch',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput().partition}:mobiletargeting:${aws.getRegionOutput().name}:${aws.getCallerIdentityOutput().accountId}:apps/${args.pinpointApplicationId}/endpoints/*`,
            ],
          },
        ],
      }
    }, opts);
    this.registerOutputs({});
  }
}