// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface RekognitionWriteOnlyAccessPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * ID of the collection
   */
  collectionId: pulumi.Input<string>;
}

/**
 * Gives permission to create collection and index faces
 */
export class RekognitionWriteOnlyAccessPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: RekognitionWriteOnlyAccessPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:RekognitionWriteOnlyAccessPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'rekognition:CreateCollection',
              'rekognition:IndexFaces',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:rekognition:${aws.getRegionOutput({}, opts).name}:${aws.getCallerIdentityOutput({}, opts).accountId}:collection/${args.collectionId}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}