// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface RekognitionDetectOnlyPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;
}

/**
 * Gives permission to detect faces, labels and text
 */
export class RekognitionDetectOnlyPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: RekognitionDetectOnlyPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:RekognitionDetectOnlyPolicy', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'rekognition:DetectFaces',
              'rekognition:DetectLabels',
              'rekognition:DetectModerationLabels',
              'rekognition:DetectText',
            ],
            Resource: [
              pulumi.interpolate`*`,
            ],
          },
        ],
      }
    }, opts);
    this.registerOutputs({});
  }
}