// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface RekognitionLabelsPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;
}

/**
 * Gives permission to detect object and moderation labels
 */
export class RekognitionLabelsPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: RekognitionLabelsPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:RekognitionLabelsPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'rekognition:DetectLabels',
              'rekognition:DetectModerationLabels',
            ],
            Resource: [
              pulumi.interpolate`*`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}