// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface S3CrudPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the Bucket
   */
  bucketName: pulumi.Input<string>;
}

/**
 * Gives CRUD permissions to objects in the S3 Bucket
 */
export class S3CrudPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: S3CrudPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:S3CrudPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              's3:GetObject',
              's3:ListBucket',
              's3:GetBucketLocation',
              's3:GetObjectVersion',
              's3:PutObject',
              's3:PutObjectAcl',
              's3:GetLifecycleConfiguration',
              's3:PutLifecycleConfiguration',
              's3:DeleteObject',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:s3:::${args.bucketName}`,
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:s3:::${args.bucketName}/*`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}