// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface S3FullAccessPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the Bucket
   */
  bucketName: pulumi.Input<string>;
}

/**
 * Gives full access permissions to objects in the S3 Bucket
 */
export class S3FullAccessPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: S3FullAccessPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:S3FullAccessPolicy', name, args, opts);
    const opt = {
      parent: this,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              's3:GetObject',
              's3:GetObjectAcl',
              's3:GetObjectVersion',
              's3:PutObject',
              's3:PutObjectAcl',
              's3:DeleteObject',
              's3:DeleteObjectTagging',
              's3:DeleteObjectVersionTagging',
              's3:GetObjectTagging',
              's3:GetObjectVersionTagging',
              's3:PutObjectTagging',
              's3:PutObjectVersionTagging',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:s3:::${args.bucketName}/*`,
            ],
          },
          {
            Effect: 'Allow',
            Action: [
              's3:ListBucket',
              's3:GetBucketLocation',
              's3:GetLifecycleConfiguration',
              's3:PutLifecycleConfiguration',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:s3:::${args.bucketName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}