// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface S3ReadPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the Bucket
   */
  bucketName: pulumi.Input<string>;
}

/**
 * Gives read permissions to objects in the S3 Bucket
 */
export class S3ReadPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: S3ReadPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:S3ReadPolicy', name, args, opts);
    const opt = {
      parent: this,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              's3:GetObject',
              's3:ListBucket',
              's3:GetBucketLocation',
              's3:GetObjectVersion',
              's3:GetLifecycleConfiguration',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:s3:::${args.bucketName}`,
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:s3:::${args.bucketName}/*`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}