// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface SageMakerCreateEndpointPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the SageMaker endpoint
   */
  endpointName: pulumi.Input<string>;
}

/**
 * Gives permission to create an endpoint in SageMaker
 */
export class SageMakerCreateEndpointPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: SageMakerCreateEndpointPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:SageMakerCreateEndpointPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'sagemaker:CreateEndpoint',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:sagemaker:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:endpoint/${args.endpointName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}