// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface SageMakerCreateEndpointConfigPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the SageMaker endpoint configuration
   */
  endpointConfigName: pulumi.Input<string>;
}

/**
 * Gives permission to create an endpoint configuration in SageMaker
 */
export class SageMakerCreateEndpointConfigPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: SageMakerCreateEndpointConfigPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:SageMakerCreateEndpointConfigPolicy', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'sagemaker:CreateEndpointConfig',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput().partition}:sagemaker:${aws.getRegionOutput().name}:${aws.getCallerIdentityOutput().accountId}:endpoint-config/${args.endpointConfigName}`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}