// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface SESBulkTemplatedCrudPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Identity to give permissions to
   */
  identityName: pulumi.Input<string>;
}

/**
 * Gives permission to send email, templated email, templated bulk emails and verify identity
 */
export class SESBulkTemplatedCrudPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: SESBulkTemplatedCrudPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:SESBulkTemplatedCrudPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'ses:GetIdentityVerificationAttributes',
              'ses:SendEmail',
              'ses:SendRawEmail',
              'ses:SendTemplatedEmail',
              'ses:SendBulkTemplatedEmail',
              'ses:VerifyEmailIdentity',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:ses:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:identity/${args.identityName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}