// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface SESSendBouncePolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Identity to give permissions to
   */
  identityName: pulumi.Input<string>;
}

/**
 * Gives SendBounce permission to a SES identity
 */
export class SESSendBouncePolicy extends pulumi.ComponentResource {
  constructor(name: string, args: SESSendBouncePolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:SESSendBouncePolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'ses:SendBounce',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput({}, opts).partition}:ses:${aws.getRegionOutput({}, opts).name}:${aws.getCallerIdentityOutput({}, opts).accountId}:identity/${args.identityName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}