// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface SNSPublishMessagePolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the SNS Topic
   */
  topicName: pulumi.Input<string>;
}

/**
 * Gives permission to publish message to SNS Topic
 */
export class SNSPublishMessagePolicy extends pulumi.ComponentResource {
  constructor(name: string, args: SNSPublishMessagePolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:SNSPublishMessagePolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'sns:Publish',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:sns:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:${args.topicName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}