// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface SQSPollerPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the SQS Queue
   */
  queueName: pulumi.Input<string>;
}

/**
 * Gives permissions to poll an SQS Queue
 */
export class SQSPollerPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: SQSPollerPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:SQSPollerPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'sqs:ChangeMessageVisibility',
              'sqs:ChangeMessageVisibilityBatch',
              'sqs:DeleteMessage',
              'sqs:DeleteMessageBatch',
              'sqs:GetQueueAttributes',
              'sqs:ReceiveMessage',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:sqs:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:${args.queueName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}