// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface SQSSendMessagePolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * Name of the SQS Queue
   */
  queueName: pulumi.Input<string>;
}

/**
 * Gives permission to send message to SQS Queue
 */
export class SQSSendMessagePolicy extends pulumi.ComponentResource {
  constructor(name: string, args: SQSSendMessagePolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:SQSSendMessagePolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'sqs:SendMessage*',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:sqs:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:${args.queueName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}