// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface SSMParameterWithSlashPrefixReadPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * The name of the secret stored in SSM in your account. Name should contain a leading slash.
   */
  parameterName: pulumi.Input<string>;
}

/**
 * Gives access to a parameter to load secrets in this account. If not using default key, KMSDecryptPolicy will also be needed.
 */
export class SSMParameterWithSlashPrefixReadPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: SSMParameterWithSlashPrefixReadPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:SSMParameterWithSlashPrefixReadPolicy', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'ssm:DescribeParameters',
            ],
            Resource: [
              pulumi.interpolate`*`,
            ],
          },
          {
            Effect: 'Allow',
            Action: [
              'ssm:GetParameters',
              'ssm:GetParameter',
              'ssm:GetParametersByPath',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:ssm:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:parameter${args.parameterName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}