// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as aws from '@pulumi/aws';
import * as pulumi from '@pulumi/pulumi';

export interface SSMParameterReadPolicyArgs {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * The name of the secret stored in SSM in your account. Name shouldn't contain a leading slash.
   */
  parameterName: pulumi.Input<string>;
}

/**
 * Gives access to a parameter to load secrets in this account. If not using default key, KMSDecryptPolicy will also be needed.
 */
export class SSMParameterReadPolicy extends pulumi.ComponentResource {
  constructor(name: string, args: SSMParameterReadPolicyArgs, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:SSMParameterReadPolicy', name, args, opts);
    new aws.iam.RolePolicy(`${name}-policy`, {
      role: args.roleName,
      policy: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'ssm:DescribeParameters',
            ],
            Resource: [
              pulumi.interpolate`*`,
            ],
          },
          {
            Effect: 'Allow',
            Action: [
              'ssm:GetParameters',
              'ssm:GetParameter',
              'ssm:GetParametersByPath',
            ],
            Resource: [
              pulumi.interpolate`arn:${aws.getPartitionOutput().partition}:ssm:${aws.getRegionOutput().name}:${aws.getCallerIdentityOutput().accountId}:parameter/${args.parameterName}`,
            ],
          },
        ],
      }
    });
    this.registerOutputs({});
  }
}