// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as ccapi from '@pulumi/aws-native';
import * as pulumi from '@pulumi/pulumi';

export interface StepFunctionsExecutionPolicy_v2Args {
  /**
   * The name of the role to attach the policy to.
   */
  roleName: pulumi.Input<string>;

  /**
   * The name of the state machine to execute.
   */
  stateMachineName: pulumi.Input<string>;
}

/**
 * Gives permission to start a Step Functions state machine execution
 */
export class StepFunctionsExecutionPolicy_v2 extends pulumi.ComponentResource {
  constructor(name: string, args: StepFunctionsExecutionPolicy_v2Args, opts?: pulumi.ComponentResourceOptions) {
    super('aws-policies:index:StepFunctionsExecutionPolicy_v2', name, args, opts);
    const opt = {
      parent: this,
      ...opts,
    };
    new ccapi.iam.RolePolicy(`${name}-policy`, {
      roleName: args.roleName,
      policyDocument: {
        Version: '2012-10-17',
        Statement: [
          {
            Effect: 'Allow',
            Action: [
              'states:StartExecution',
              'states:StartSyncExecution',
            ],
            Resource: [
              pulumi.interpolate`arn:${ccapi.getPartitionOutput(opt).partition}:states:${ccapi.getRegionOutput(opt).region}:${ccapi.getAccountIdOutput(opt).accountId}:stateMachine:${args.stateMachineName}`,
            ],
          },
        ],
      }
    }, opt);
    this.registerOutputs({});
  }
}